apiVersion: v1
kind: Service
metadata:
  name: memos
  namespace: memos
  labels:
    app: memos
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 5230
      targetPort: 5230
      protocol: TCP
  selector:
    app: memos
